# DD image tag
tag: 2.42.1
createSecret: true
createRedisSecret: true
createPostgresqlSecret: true
# Primary hostname of instance
host: defectdojo.129.212.146.77.sslip.io
# Django params
django:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    activateTLS: false