createSecret: true
createRedisSecret: true
createPostgresqlSecret: true
host: defectdojo.129.212.146.218.sslip.io
django:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    activateTLS: false